### ISSUE TITLE
DeprecationWarning: invalid escape sequence

### ISSUE THREAD

**Issue by ShaheedHaque** [mysociety/uk-postcode-utils#4]
Hi,

Recent Python gives warnings about the use of \d in a non-raw string such as here:

https://github.com/mysociety/uk-postcode-utils/blob/77e5f6b4554d103670416773379f82f94da06e30/ukpostcodeutils/validation.py#L13

It would be lovely to have a fix. I could do a PR if that would help...

**Comment by dracos** [comment]
If you'd like to do a PR, that'd be great, thanks, otherwise I can hopefully take a look in the near future, thanks for letting us know.

**Comment by ShaheedHaque** [comment]
That would be great.

**Comment by ShaheedHaque** [comment]
Gentle nudge...anyone feel like merging the PR and releasing?

**Comment by dracos** [comment]
Sorry! Merged now, will push to pypi in a sec when I remember how to do it.

**Comment by ShaheedHaque** [comment]
Many thanks...
